/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AnalyticsCustomerMetric
    /// </summary>
    [DataContract(Name = "Analytics_CustomerMetric")]
    public partial class AnalyticsCustomerMetric : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsCustomerMetric" /> class.
        /// </summary>
        /// <param name="ordersCount">ordersCount.</param>
        /// <param name="totalSpend">totalSpend.</param>
        /// <param name="avgOrderValue">avgOrderValue.</param>
        /// <param name="currencyId">currencyId.</param>
        /// <param name="additionalFields">additionalFields.</param>
        /// <param name="customFields">customFields.</param>
        public AnalyticsCustomerMetric(int? ordersCount = default(int?), decimal? totalSpend = default(decimal?), decimal? avgOrderValue = default(decimal?), string currencyId = default(string), Object additionalFields = default(Object), Object customFields = default(Object))
        {
            this.OrdersCount = ordersCount;
            this.TotalSpend = totalSpend;
            this.AvgOrderValue = avgOrderValue;
            this.CurrencyId = currencyId;
            this.AdditionalFields = additionalFields;
            this.CustomFields = customFields;
        }

        /// <summary>
        /// Gets or Sets OrdersCount
        /// </summary>
        [DataMember(Name = "orders_count", EmitDefaultValue = true)]
        public int? OrdersCount { get; set; }

        /// <summary>
        /// Gets or Sets TotalSpend
        /// </summary>
        [DataMember(Name = "total_spend", EmitDefaultValue = true)]
        public decimal? TotalSpend { get; set; }

        /// <summary>
        /// Gets or Sets AvgOrderValue
        /// </summary>
        [DataMember(Name = "avg_order_value", EmitDefaultValue = true)]
        public decimal? AvgOrderValue { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyId
        /// </summary>
        [DataMember(Name = "currency_id", EmitDefaultValue = true)]
        public string CurrencyId { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalFields
        /// </summary>
        [DataMember(Name = "additional_fields", EmitDefaultValue = true)]
        public Object AdditionalFields { get; set; }

        /// <summary>
        /// Gets or Sets CustomFields
        /// </summary>
        [DataMember(Name = "custom_fields", EmitDefaultValue = true)]
        public Object CustomFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsCustomerMetric {\n");
            sb.Append("  OrdersCount: ").Append(OrdersCount).Append("\n");
            sb.Append("  TotalSpend: ").Append(TotalSpend).Append("\n");
            sb.Append("  AvgOrderValue: ").Append(AvgOrderValue).Append("\n");
            sb.Append("  CurrencyId: ").Append(CurrencyId).Append("\n");
            sb.Append("  AdditionalFields: ").Append(AdditionalFields).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
