/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// OrderAddOrderItemInnerOrderItemPropertyInner
    /// </summary>
    [DataContract(Name = "OrderAdd_order_item_inner_order_item_property_inner")]
    public partial class OrderAddOrderItemInnerOrderItemPropertyInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderAddOrderItemInnerOrderItemPropertyInner" /> class.
        /// </summary>
        /// <param name="orderItemPropertyName">Ordered product property name. Where x is order item ID, y is order item property ID.</param>
        /// <param name="orderItemPropertyValue">Ordered product property value. Where x is order item ID, y - order item property ID.</param>
        public OrderAddOrderItemInnerOrderItemPropertyInner(string orderItemPropertyName = default(string), string orderItemPropertyValue = default(string))
        {
            this.OrderItemPropertyName = orderItemPropertyName;
            this.OrderItemPropertyValue = orderItemPropertyValue;
        }

        /// <summary>
        /// Ordered product property name. Where x is order item ID, y is order item property ID
        /// </summary>
        /// <value>Ordered product property name. Where x is order item ID, y is order item property ID</value>
        /*
        <example>Engraving</example>
        */
        [DataMember(Name = "order_item_property_name", EmitDefaultValue = false)]
        public string OrderItemPropertyName { get; set; }

        /// <summary>
        /// Ordered product property value. Where x is order item ID, y - order item property ID
        /// </summary>
        /// <value>Ordered product property value. Where x is order item ID, y - order item property ID</value>
        /*
        <example>lorem ipsum</example>
        */
        [DataMember(Name = "order_item_property_value", EmitDefaultValue = false)]
        public string OrderItemPropertyValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderAddOrderItemInnerOrderItemPropertyInner {\n");
            sb.Append("  OrderItemPropertyName: ").Append(OrderItemPropertyName).Append("\n");
            sb.Append("  OrderItemPropertyValue: ").Append(OrderItemPropertyValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
