/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ParamDefinitionFilteringConditionsFilterCondition
    /// </summary>
    [JsonConverter(typeof(ParamDefinitionFilteringConditionsFilterConditionJsonConverter))]
    [DataContract(Name = "ParamDefinition_FilteringConditions_FilterCondition")]
    public partial class ParamDefinitionFilteringConditionsFilterCondition : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParamDefinitionFilteringConditionsFilterCondition" /> class
        /// with the <see cref="ParamDefinitionFilteringConditionsFilterGroup" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ParamDefinitionFilteringConditionsFilterGroup.</param>
        public ParamDefinitionFilteringConditionsFilterCondition(ParamDefinitionFilteringConditionsFilterGroup actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ParamDefinitionFilteringConditionsFilterCondition" /> class
        /// with the <see cref="ParamDefinitionFilteringConditionsFilterRule" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ParamDefinitionFilteringConditionsFilterRule.</param>
        public ParamDefinitionFilteringConditionsFilterCondition(ParamDefinitionFilteringConditionsFilterRule actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ParamDefinitionFilteringConditionsFilterGroup) || value is ParamDefinitionFilteringConditionsFilterGroup)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ParamDefinitionFilteringConditionsFilterRule) || value is ParamDefinitionFilteringConditionsFilterRule)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ParamDefinitionFilteringConditionsFilterGroup, ParamDefinitionFilteringConditionsFilterRule");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ParamDefinitionFilteringConditionsFilterGroup`. If the actual instance is not `ParamDefinitionFilteringConditionsFilterGroup`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ParamDefinitionFilteringConditionsFilterGroup</returns>
        public ParamDefinitionFilteringConditionsFilterGroup GetParamDefinitionFilteringConditionsFilterGroup()
        {
            return (ParamDefinitionFilteringConditionsFilterGroup)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ParamDefinitionFilteringConditionsFilterRule`. If the actual instance is not `ParamDefinitionFilteringConditionsFilterRule`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ParamDefinitionFilteringConditionsFilterRule</returns>
        public ParamDefinitionFilteringConditionsFilterRule GetParamDefinitionFilteringConditionsFilterRule()
        {
            return (ParamDefinitionFilteringConditionsFilterRule)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParamDefinitionFilteringConditionsFilterCondition {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ParamDefinitionFilteringConditionsFilterCondition.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ParamDefinitionFilteringConditionsFilterCondition
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ParamDefinitionFilteringConditionsFilterCondition</returns>
        public static ParamDefinitionFilteringConditionsFilterCondition FromJson(string jsonString)
        {
            ParamDefinitionFilteringConditionsFilterCondition newParamDefinitionFilteringConditionsFilterCondition = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newParamDefinitionFilteringConditionsFilterCondition;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ParamDefinitionFilteringConditionsFilterGroup).GetProperty("AdditionalProperties") == null)
                {
                    newParamDefinitionFilteringConditionsFilterCondition = new ParamDefinitionFilteringConditionsFilterCondition(JsonConvert.DeserializeObject<ParamDefinitionFilteringConditionsFilterGroup>(jsonString, ParamDefinitionFilteringConditionsFilterCondition.SerializerSettings));
                }
                else
                {
                    newParamDefinitionFilteringConditionsFilterCondition = new ParamDefinitionFilteringConditionsFilterCondition(JsonConvert.DeserializeObject<ParamDefinitionFilteringConditionsFilterGroup>(jsonString, ParamDefinitionFilteringConditionsFilterCondition.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ParamDefinitionFilteringConditionsFilterGroup");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ParamDefinitionFilteringConditionsFilterGroup: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ParamDefinitionFilteringConditionsFilterRule).GetProperty("AdditionalProperties") == null)
                {
                    newParamDefinitionFilteringConditionsFilterCondition = new ParamDefinitionFilteringConditionsFilterCondition(JsonConvert.DeserializeObject<ParamDefinitionFilteringConditionsFilterRule>(jsonString, ParamDefinitionFilteringConditionsFilterCondition.SerializerSettings));
                }
                else
                {
                    newParamDefinitionFilteringConditionsFilterCondition = new ParamDefinitionFilteringConditionsFilterCondition(JsonConvert.DeserializeObject<ParamDefinitionFilteringConditionsFilterRule>(jsonString, ParamDefinitionFilteringConditionsFilterCondition.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ParamDefinitionFilteringConditionsFilterRule");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ParamDefinitionFilteringConditionsFilterRule: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newParamDefinitionFilteringConditionsFilterCondition;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ParamDefinitionFilteringConditionsFilterCondition
    /// </summary>
    public class ParamDefinitionFilteringConditionsFilterConditionJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ParamDefinitionFilteringConditionsFilterCondition).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return ParamDefinitionFilteringConditionsFilterCondition.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return ParamDefinitionFilteringConditionsFilterCondition.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
