/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ProductAddBatchPayloadInnerSalesTax
    /// </summary>
    [DataContract(Name = "ProductAddBatch_payload_inner_sales_tax")]
    public partial class ProductAddBatchPayloadInnerSalesTax : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductAddBatchPayloadInnerSalesTax" /> class.
        /// </summary>
        /// <param name="taxPercent">taxPercent.</param>
        /// <param name="taxable">taxable.</param>
        public ProductAddBatchPayloadInnerSalesTax(decimal taxPercent = default(decimal), bool taxable = default(bool))
        {
            this.TaxPercent = taxPercent;
            this.Taxable = taxable;
        }

        /// <summary>
        /// Gets or Sets TaxPercent
        /// </summary>
        [DataMember(Name = "tax_percent", EmitDefaultValue = false)]
        public decimal TaxPercent { get; set; }

        /// <summary>
        /// Gets or Sets Taxable
        /// </summary>
        [DataMember(Name = "taxable", EmitDefaultValue = true)]
        public bool Taxable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductAddBatchPayloadInnerSalesTax {\n");
            sb.Append("  TaxPercent: ").Append(TaxPercent).Append("\n");
            sb.Append("  Taxable: ").Append(Taxable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TaxPercent (decimal) minimum
            if (this.TaxPercent < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for TaxPercent, must be a value greater than or equal to 0.", new [] { "TaxPercent" });
            }

            yield break;
        }
    }

}
