name: Update csharp SDK

# Запускати вручну (workflow_dispatch) або за розкладом (schedule).
on:
  schedule:
    # Раз на добу о 00:00 за UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

# Потрібні права на запис у репозиторій.
permissions:
  contents: write

jobs:
  update_csharp_sdk:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Клонуємо ваш репозиторій
      - name: Checkout repository
        uses: actions/checkout@v3

      # Крок 2: Завантажуємо архів
      - name: Download csharp.tgz
        run: |
          curl -L -o csharp.tgz https://app.api2cart.com/sdk/openapi/csharp.tgz

      # Крок 3: Розпаковуємо архів у корінь репозиторію 
      - name: Extract csharp.tgz
        run: |
          tar -xzf csharp.tgz

      # Крок 4: Комітимо і пушимо зміни (якщо вони є)
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          # Перевіримо, чи є що комітити
          git diff-index --quiet HEAD || git commit -m "Update csharp SDK [skip ci]"
          git push
