/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ProductDeleteBatch
    /// </summary>
    [DataContract(Name = "ProductDeleteBatch")]
    public partial class ProductDeleteBatch : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDeleteBatch" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProductDeleteBatch() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDeleteBatch" /> class.
        /// </summary>
        /// <param name="payload">Contains an array of product deletion requests, each including the product ID. (required).</param>
        public ProductDeleteBatch(List<ProductDeleteBatchPayloadInner> payload = default(List<ProductDeleteBatchPayloadInner>))
        {
            // to ensure "payload" is required (not null)
            if (payload == null)
            {
                throw new ArgumentNullException("payload is a required property for ProductDeleteBatch and cannot be null");
            }
            this.Payload = payload;
        }

        /// <summary>
        /// Contains an array of product deletion requests, each including the product ID.
        /// </summary>
        /// <value>Contains an array of product deletion requests, each including the product ID.</value>
        [DataMember(Name = "payload", IsRequired = true, EmitDefaultValue = true)]
        public List<ProductDeleteBatchPayloadInner> Payload { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductDeleteBatch {\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
