/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ProductVariantAddBatch
    /// </summary>
    [DataContract(Name = "ProductVariantAddBatch")]
    public partial class ProductVariantAddBatch : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductVariantAddBatch" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProductVariantAddBatch() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductVariantAddBatch" /> class.
        /// </summary>
        /// <param name="clearCache">clearCache (default to false).</param>
        /// <param name="reindex">reindex (default to false).</param>
        /// <param name="payload">Contains an array of product variants objects. The list of properties may vary depending on the specific platform. (required).</param>
        public ProductVariantAddBatch(bool clearCache = false, bool reindex = false, List<ProductVariantAddBatchPayloadInner> payload = default(List<ProductVariantAddBatchPayloadInner>))
        {
            // to ensure "payload" is required (not null)
            if (payload == null)
            {
                throw new ArgumentNullException("payload is a required property for ProductVariantAddBatch and cannot be null");
            }
            this.Payload = payload;
            this.ClearCache = clearCache;
            this.Reindex = reindex;
        }

        /// <summary>
        /// Gets or Sets ClearCache
        /// </summary>
        [DataMember(Name = "clear_cache", EmitDefaultValue = true)]
        public bool ClearCache { get; set; }

        /// <summary>
        /// Gets or Sets Reindex
        /// </summary>
        [DataMember(Name = "reindex", EmitDefaultValue = true)]
        public bool Reindex { get; set; }

        /// <summary>
        /// Contains an array of product variants objects. The list of properties may vary depending on the specific platform.
        /// </summary>
        /// <value>Contains an array of product variants objects. The list of properties may vary depending on the specific platform.</value>
        [DataMember(Name = "payload", IsRequired = true, EmitDefaultValue = true)]
        public List<ProductVariantAddBatchPayloadInner> Payload { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductVariantAddBatch {\n");
            sb.Append("  ClearCache: ").Append(ClearCache).Append("\n");
            sb.Append("  Reindex: ").Append(Reindex).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
