/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ProductTaxAdd
    /// </summary>
    [DataContract(Name = "ProductTaxAdd")]
    public partial class ProductTaxAdd : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductTaxAdd" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProductTaxAdd() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductTaxAdd" /> class.
        /// </summary>
        /// <param name="productId">Defines products specified by product id.</param>
        /// <param name="name">Defines tax class name where tax has to be added (required).</param>
        /// <param name="taxRates">Defines tax rates of specified tax classes (required).</param>
        public ProductTaxAdd(string productId = default(string), string name = default(string), List<ProductTaxAddTaxRatesInner> taxRates = default(List<ProductTaxAddTaxRatesInner>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ProductTaxAdd and cannot be null");
            }
            this.Name = name;
            // to ensure "taxRates" is required (not null)
            if (taxRates == null)
            {
                throw new ArgumentNullException("taxRates is a required property for ProductTaxAdd and cannot be null");
            }
            this.TaxRates = taxRates;
            this.ProductId = productId;
        }

        /// <summary>
        /// Defines products specified by product id
        /// </summary>
        /// <value>Defines products specified by product id</value>
        /*
        <example>10</example>
        */
        [DataMember(Name = "product_id", EmitDefaultValue = false)]
        public string ProductId { get; set; }

        /// <summary>
        /// Defines tax class name where tax has to be added
        /// </summary>
        /// <value>Defines tax class name where tax has to be added</value>
        /*
        <example>ECO-Tax</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Defines tax rates of specified tax classes
        /// </summary>
        /// <value>Defines tax rates of specified tax classes</value>
        [DataMember(Name = "tax_rates", IsRequired = true, EmitDefaultValue = true)]
        public List<ProductTaxAddTaxRatesInner> TaxRates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductTaxAdd {\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  TaxRates: ").Append(TaxRates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
