/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CartShippingZone2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartShippingZone2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartShippingZone2
        //private CartShippingZone2 instance;

        public CartShippingZone2Tests()
        {
            // TODO uncomment below to create an instance of CartShippingZone2
            //instance = new CartShippingZone2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartShippingZone2
        /// </summary>
        [Fact]
        public void CartShippingZone2InstanceTest()
        {
            // TODO uncomment below to test "IsType" CartShippingZone2
            //Assert.IsType<CartShippingZone2>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Countries'
        /// </summary>
        [Fact]
        public void CountriesTest()
        {
            // TODO unit test for the property 'Countries'
        }

        /// <summary>
        /// Test the property 'ShippingMethods'
        /// </summary>
        [Fact]
        public void ShippingMethodsTest()
        {
            // TODO unit test for the property 'ShippingMethods'
        }

        /// <summary>
        /// Test the property 'AdditionalFields'
        /// </summary>
        [Fact]
        public void AdditionalFieldsTest()
        {
            // TODO unit test for the property 'AdditionalFields'
        }

        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
    }
}
