/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ModelResponseCategoryList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelResponseCategoryListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelResponseCategoryList
        //private ModelResponseCategoryList instance;

        public ModelResponseCategoryListTests()
        {
            // TODO uncomment below to create an instance of ModelResponseCategoryList
            //instance = new ModelResponseCategoryList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelResponseCategoryList
        /// </summary>
        [Fact]
        public void ModelResponseCategoryListInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelResponseCategoryList
            //Assert.IsType<ModelResponseCategoryList>(instance);
        }

        /// <summary>
        /// Test the property 'ReturnCode'
        /// </summary>
        [Fact]
        public void ReturnCodeTest()
        {
            // TODO unit test for the property 'ReturnCode'
        }

        /// <summary>
        /// Test the property 'ReturnMessage'
        /// </summary>
        [Fact]
        public void ReturnMessageTest()
        {
            // TODO unit test for the property 'ReturnMessage'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

        /// <summary>
        /// Test the property 'AdditionalFields'
        /// </summary>
        [Fact]
        public void AdditionalFieldsTest()
        {
            // TODO unit test for the property 'AdditionalFields'
        }

        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
    }
}
