/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProductAddGroupPricesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductAddGroupPricesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductAddGroupPricesInner
        //private ProductAddGroupPricesInner instance;

        public ProductAddGroupPricesInnerTests()
        {
            // TODO uncomment below to create an instance of ProductAddGroupPricesInner
            //instance = new ProductAddGroupPricesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductAddGroupPricesInner
        /// </summary>
        [Fact]
        public void ProductAddGroupPricesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductAddGroupPricesInner
            //Assert.IsType<ProductAddGroupPricesInner>(instance);
        }

        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Fact]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
    }
}
