/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProductOptionAddValuesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductOptionAddValuesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductOptionAddValuesInner
        //private ProductOptionAddValuesInner instance;

        public ProductOptionAddValuesInnerTests()
        {
            // TODO uncomment below to create an instance of ProductOptionAddValuesInner
            //instance = new ProductOptionAddValuesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductOptionAddValuesInner
        /// </summary>
        [Fact]
        public void ProductOptionAddValuesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductOptionAddValuesInner
            //Assert.IsType<ProductOptionAddValuesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'DisplayValue'
        /// </summary>
        [Fact]
        public void DisplayValueTest()
        {
            // TODO unit test for the property 'DisplayValue'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }
    }
}
