/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProductVariantAddBatchPayloadInnerCombinationInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductVariantAddBatchPayloadInnerCombinationInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductVariantAddBatchPayloadInnerCombinationInner
        //private ProductVariantAddBatchPayloadInnerCombinationInner instance;

        public ProductVariantAddBatchPayloadInnerCombinationInnerTests()
        {
            // TODO uncomment below to create an instance of ProductVariantAddBatchPayloadInnerCombinationInner
            //instance = new ProductVariantAddBatchPayloadInnerCombinationInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductVariantAddBatchPayloadInnerCombinationInner
        /// </summary>
        [Fact]
        public void ProductVariantAddBatchPayloadInnerCombinationInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductVariantAddBatchPayloadInnerCombinationInner
            //Assert.IsType<ProductVariantAddBatchPayloadInnerCombinationInner>(instance);
        }

        /// <summary>
        /// Test the property 'OptionName'
        /// </summary>
        [Fact]
        public void OptionNameTest()
        {
            // TODO unit test for the property 'OptionName'
        }

        /// <summary>
        /// Test the property 'OptionValueName'
        /// </summary>
        [Fact]
        public void OptionValueNameTest()
        {
            // TODO unit test for the property 'OptionValueName'
        }
    }
}
