/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams
        //private AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams instance;

        public AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParamsTests()
        {
            // TODO uncomment below to create an instance of AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams
            //instance = new AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams
        /// </summary>
        [Fact]
        public void AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams
            //Assert.IsType<AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams>(instance);
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

        /// <summary>
        /// Test the property 'Additional'
        /// </summary>
        [Fact]
        public void AdditionalTest()
        {
            // TODO unit test for the property 'Additional'
        }
    }
}
