/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BasketLiveShippingServiceList200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BasketLiveShippingServiceList200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BasketLiveShippingServiceList200Response
        //private BasketLiveShippingServiceList200Response instance;

        public BasketLiveShippingServiceList200ResponseTests()
        {
            // TODO uncomment below to create an instance of BasketLiveShippingServiceList200Response
            //instance = new BasketLiveShippingServiceList200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BasketLiveShippingServiceList200Response
        /// </summary>
        [Fact]
        public void BasketLiveShippingServiceList200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BasketLiveShippingServiceList200Response
            //Assert.IsType<BasketLiveShippingServiceList200Response>(instance);
        }

        /// <summary>
        /// Test the property 'ReturnCode'
        /// </summary>
        [Fact]
        public void ReturnCodeTest()
        {
            // TODO unit test for the property 'ReturnCode'
        }

        /// <summary>
        /// Test the property 'ReturnMessage'
        /// </summary>
        [Fact]
        public void ReturnMessageTest()
        {
            // TODO unit test for the property 'ReturnMessage'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
    }
}
