/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CategoryAddBatch200ResponseResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CategoryAddBatch200ResponseResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CategoryAddBatch200ResponseResult
        //private CategoryAddBatch200ResponseResult instance;

        public CategoryAddBatch200ResponseResultTests()
        {
            // TODO uncomment below to create an instance of CategoryAddBatch200ResponseResult
            //instance = new CategoryAddBatch200ResponseResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CategoryAddBatch200ResponseResult
        /// </summary>
        [Fact]
        public void CategoryAddBatch200ResponseResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" CategoryAddBatch200ResponseResult
            //Assert.IsType<CategoryAddBatch200ResponseResult>(instance);
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
    }
}
