/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CategoryDeleteBatchPayloadInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CategoryDeleteBatchPayloadInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CategoryDeleteBatchPayloadInner
        //private CategoryDeleteBatchPayloadInner instance;

        public CategoryDeleteBatchPayloadInnerTests()
        {
            // TODO uncomment below to create an instance of CategoryDeleteBatchPayloadInner
            //instance = new CategoryDeleteBatchPayloadInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CategoryDeleteBatchPayloadInner
        /// </summary>
        [Fact]
        public void CategoryDeleteBatchPayloadInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CategoryDeleteBatchPayloadInner
            //Assert.IsType<CategoryDeleteBatchPayloadInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
