/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CategoryFind200ResponseResultCategoryInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CategoryFind200ResponseResultCategoryInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CategoryFind200ResponseResultCategoryInner
        //private CategoryFind200ResponseResultCategoryInner instance;

        public CategoryFind200ResponseResultCategoryInnerTests()
        {
            // TODO uncomment below to create an instance of CategoryFind200ResponseResultCategoryInner
            //instance = new CategoryFind200ResponseResultCategoryInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CategoryFind200ResponseResultCategoryInner
        /// </summary>
        [Fact]
        public void CategoryFind200ResponseResultCategoryInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CategoryFind200ResponseResultCategoryInner
            //Assert.IsType<CategoryFind200ResponseResultCategoryInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
