/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CategoryAddBatchPayloadInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CategoryAddBatchPayloadInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CategoryAddBatchPayloadInner
        //private CategoryAddBatchPayloadInner instance;

        public CategoryAddBatchPayloadInnerTests()
        {
            // TODO uncomment below to create an instance of CategoryAddBatchPayloadInner
            //instance = new CategoryAddBatchPayloadInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CategoryAddBatchPayloadInner
        /// </summary>
        [Fact]
        public void CategoryAddBatchPayloadInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CategoryAddBatchPayloadInner
            //Assert.IsType<CategoryAddBatchPayloadInner>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Avail'
        /// </summary>
        [Fact]
        public void AvailTest()
        {
            // TODO unit test for the property 'Avail'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'MetaTitle'
        /// </summary>
        [Fact]
        public void MetaTitleTest()
        {
            // TODO unit test for the property 'MetaTitle'
        }

        /// <summary>
        /// Test the property 'MetaDescription'
        /// </summary>
        [Fact]
        public void MetaDescriptionTest()
        {
            // TODO unit test for the property 'MetaDescription'
        }

        /// <summary>
        /// Test the property 'MetaKeywords'
        /// </summary>
        [Fact]
        public void MetaKeywordsTest()
        {
            // TODO unit test for the property 'MetaKeywords'
        }

        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Fact]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }

        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Fact]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

        /// <summary>
        /// Test the property 'SeoUrl'
        /// </summary>
        [Fact]
        public void SeoUrlTest()
        {
            // TODO unit test for the property 'SeoUrl'
        }

        /// <summary>
        /// Test the property 'StoreId'
        /// </summary>
        [Fact]
        public void StoreIdTest()
        {
            // TODO unit test for the property 'StoreId'
        }

        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Fact]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }

        /// <summary>
        /// Test the property 'StoresIds'
        /// </summary>
        [Fact]
        public void StoresIdsTest()
        {
            // TODO unit test for the property 'StoresIds'
        }
    }
}
