/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CategoryAddBatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CategoryAddBatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CategoryAddBatch
        //private CategoryAddBatch instance;

        public CategoryAddBatchTests()
        {
            // TODO uncomment below to create an instance of CategoryAddBatch
            //instance = new CategoryAddBatch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CategoryAddBatch
        /// </summary>
        [Fact]
        public void CategoryAddBatchInstanceTest()
        {
            // TODO uncomment below to test "IsType" CategoryAddBatch
            //Assert.IsType<CategoryAddBatch>(instance);
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
    }
}
