/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderShipmentUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderShipmentUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderShipmentUpdate
        //private OrderShipmentUpdate instance;

        public OrderShipmentUpdateTests()
        {
            // TODO uncomment below to create an instance of OrderShipmentUpdate
            //instance = new OrderShipmentUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderShipmentUpdate
        /// </summary>
        [Fact]
        public void OrderShipmentUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderShipmentUpdate
            //Assert.IsType<OrderShipmentUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Fact]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }

        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }

        /// <summary>
        /// Test the property 'StoreId'
        /// </summary>
        [Fact]
        public void StoreIdTest()
        {
            // TODO unit test for the property 'StoreId'
        }

        /// <summary>
        /// Test the property 'ShipmentProvider'
        /// </summary>
        [Fact]
        public void ShipmentProviderTest()
        {
            // TODO unit test for the property 'ShipmentProvider'
        }

        /// <summary>
        /// Test the property 'TrackingNumbers'
        /// </summary>
        [Fact]
        public void TrackingNumbersTest()
        {
            // TODO unit test for the property 'TrackingNumbers'
        }

        /// <summary>
        /// Test the property 'TrackingLink'
        /// </summary>
        [Fact]
        public void TrackingLinkTest()
        {
            // TODO unit test for the property 'TrackingLink'
        }

        /// <summary>
        /// Test the property 'IsShipped'
        /// </summary>
        [Fact]
        public void IsShippedTest()
        {
            // TODO unit test for the property 'IsShipped'
        }

        /// <summary>
        /// Test the property 'DeliveredAt'
        /// </summary>
        [Fact]
        public void DeliveredAtTest()
        {
            // TODO unit test for the property 'DeliveredAt'
        }

        /// <summary>
        /// Test the property 'Replace'
        /// </summary>
        [Fact]
        public void ReplaceTest()
        {
            // TODO unit test for the property 'Replace'
        }

        /// <summary>
        /// Test the property 'SendNotifications'
        /// </summary>
        [Fact]
        public void SendNotificationsTest()
        {
            // TODO unit test for the property 'SendNotifications'
        }

        /// <summary>
        /// Test the property 'TrackingProvider'
        /// </summary>
        [Fact]
        public void TrackingProviderTest()
        {
            // TODO unit test for the property 'TrackingProvider'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
    }
}
