/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCalculateBundle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCalculateBundleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCalculateBundle
        //private OrderCalculateBundle instance;

        public OrderCalculateBundleTests()
        {
            // TODO uncomment below to create an instance of OrderCalculateBundle
            //instance = new OrderCalculateBundle();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCalculateBundle
        /// </summary>
        [Fact]
        public void OrderCalculateBundleInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCalculateBundle
            //Assert.IsType<OrderCalculateBundle>(instance);
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Fact]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'PriceIncTax'
        /// </summary>
        [Fact]
        public void PriceIncTaxTest()
        {
            // TODO unit test for the property 'PriceIncTax'
        }

        /// <summary>
        /// Test the property 'TaxRate'
        /// </summary>
        [Fact]
        public void TaxRateTest()
        {
            // TODO unit test for the property 'TaxRate'
        }

        /// <summary>
        /// Test the property 'UnitDiscount'
        /// </summary>
        [Fact]
        public void UnitDiscountTest()
        {
            // TODO unit test for the property 'UnitDiscount'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

        /// <summary>
        /// Test the property 'WeightUnit'
        /// </summary>
        [Fact]
        public void WeightUnitTest()
        {
            // TODO unit test for the property 'WeightUnit'
        }

        /// <summary>
        /// Test the property 'Barcode'
        /// </summary>
        [Fact]
        public void BarcodeTest()
        {
            // TODO unit test for the property 'Barcode'
        }

        /// <summary>
        /// Test the property 'VariantId'
        /// </summary>
        [Fact]
        public void VariantIdTest()
        {
            // TODO unit test for the property 'VariantId'
        }

        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

        /// <summary>
        /// Test the property 'AdditionalFields'
        /// </summary>
        [Fact]
        public void AdditionalFieldsTest()
        {
            // TODO unit test for the property 'AdditionalFields'
        }

        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
    }
}
