/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProductAddPersonalizationDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductAddPersonalizationDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductAddPersonalizationDetails
        //private ProductAddPersonalizationDetails instance;

        public ProductAddPersonalizationDetailsTests()
        {
            // TODO uncomment below to create an instance of ProductAddPersonalizationDetails
            //instance = new ProductAddPersonalizationDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductAddPersonalizationDetails
        /// </summary>
        [Fact]
        public void ProductAddPersonalizationDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductAddPersonalizationDetails
            //Assert.IsType<ProductAddPersonalizationDetails>(instance);
        }

        /// <summary>
        /// Test the property 'IsPersonalizable'
        /// </summary>
        [Fact]
        public void IsPersonalizableTest()
        {
            // TODO unit test for the property 'IsPersonalizable'
        }

        /// <summary>
        /// Test the property 'PersonalizationIsRequired'
        /// </summary>
        [Fact]
        public void PersonalizationIsRequiredTest()
        {
            // TODO unit test for the property 'PersonalizationIsRequired'
        }

        /// <summary>
        /// Test the property 'PersonalizationCharCountMax'
        /// </summary>
        [Fact]
        public void PersonalizationCharCountMaxTest()
        {
            // TODO unit test for the property 'PersonalizationCharCountMax'
        }

        /// <summary>
        /// Test the property 'PersonalizationInstructions'
        /// </summary>
        [Fact]
        public void PersonalizationInstructionsTest()
        {
            // TODO unit test for the property 'PersonalizationInstructions'
        }
    }
}
