/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProductImageAdd
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductImageAddTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductImageAdd
        //private ProductImageAdd instance;

        public ProductImageAddTests()
        {
            // TODO uncomment below to create an instance of ProductImageAdd
            //instance = new ProductImageAdd();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductImageAdd
        /// </summary>
        [Fact]
        public void ProductImageAddInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductImageAdd
            //Assert.IsType<ProductImageAdd>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'ImageName'
        /// </summary>
        [Fact]
        public void ImageNameTest()
        {
            // TODO unit test for the property 'ImageName'
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'ProductVariantId'
        /// </summary>
        [Fact]
        public void ProductVariantIdTest()
        {
            // TODO unit test for the property 'ProductVariantId'
        }

        /// <summary>
        /// Test the property 'VariantIds'
        /// </summary>
        [Fact]
        public void VariantIdsTest()
        {
            // TODO unit test for the property 'VariantIds'
        }

        /// <summary>
        /// Test the property 'OptionValueIds'
        /// </summary>
        [Fact]
        public void OptionValueIdsTest()
        {
            // TODO unit test for the property 'OptionValueIds'
        }

        /// <summary>
        /// Test the property 'StoreId'
        /// </summary>
        [Fact]
        public void StoreIdTest()
        {
            // TODO unit test for the property 'StoreId'
        }

        /// <summary>
        /// Test the property 'LangId'
        /// </summary>
        [Fact]
        public void LangIdTest()
        {
            // TODO unit test for the property 'LangId'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Mime'
        /// </summary>
        [Fact]
        public void MimeTest()
        {
            // TODO unit test for the property 'Mime'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'UseLatestApiVersion'
        /// </summary>
        [Fact]
        public void UseLatestApiVersionTest()
        {
            // TODO unit test for the property 'UseLatestApiVersion'
        }
    }
}
