/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProductVariantList200ResponseResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductVariantList200ResponseResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductVariantList200ResponseResult
        //private ProductVariantList200ResponseResult instance;

        public ProductVariantList200ResponseResultTests()
        {
            // TODO uncomment below to create an instance of ProductVariantList200ResponseResult
            //instance = new ProductVariantList200ResponseResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductVariantList200ResponseResult
        /// </summary>
        [Fact]
        public void ProductVariantList200ResponseResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductVariantList200ResponseResult
            //Assert.IsType<ProductVariantList200ResponseResult>(instance);
        }

        /// <summary>
        /// Test the property 'Variant'
        /// </summary>
        [Fact]
        public void VariantTest()
        {
            // TODO unit test for the property 'Variant'
        }
    }
}
