/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProductAddBatchPayloadInnerImagesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductAddBatchPayloadInnerImagesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductAddBatchPayloadInnerImagesInner
        //private ProductAddBatchPayloadInnerImagesInner instance;

        public ProductAddBatchPayloadInnerImagesInnerTests()
        {
            // TODO uncomment below to create an instance of ProductAddBatchPayloadInnerImagesInner
            //instance = new ProductAddBatchPayloadInnerImagesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductAddBatchPayloadInnerImagesInner
        /// </summary>
        [Fact]
        public void ProductAddBatchPayloadInnerImagesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductAddBatchPayloadInnerImagesInner
            //Assert.IsType<ProductAddBatchPayloadInnerImagesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
    }
}
