/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProductAddBestOffer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductAddBestOfferTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductAddBestOffer
        //private ProductAddBestOffer instance;

        public ProductAddBestOfferTests()
        {
            // TODO uncomment below to create an instance of ProductAddBestOffer
            //instance = new ProductAddBestOffer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductAddBestOffer
        /// </summary>
        [Fact]
        public void ProductAddBestOfferInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductAddBestOffer
            //Assert.IsType<ProductAddBestOffer>(instance);
        }

        /// <summary>
        /// Test the property 'MinimumOfferPrice'
        /// </summary>
        [Fact]
        public void MinimumOfferPriceTest()
        {
            // TODO unit test for the property 'MinimumOfferPrice'
        }

        /// <summary>
        /// Test the property 'AutoAcceptPrice'
        /// </summary>
        [Fact]
        public void AutoAcceptPriceTest()
        {
            // TODO unit test for the property 'AutoAcceptPrice'
        }
    }
}
