/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseReturnCountResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseReturnCountResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseReturnCountResult
        //private ResponseReturnCountResult instance;

        public ResponseReturnCountResultTests()
        {
            // TODO uncomment below to create an instance of ResponseReturnCountResult
            //instance = new ResponseReturnCountResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseReturnCountResult
        /// </summary>
        [Fact]
        public void ResponseReturnCountResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseReturnCountResult
            //Assert.IsType<ResponseReturnCountResult>(instance);
        }

        /// <summary>
        /// Test the property 'ReturnsCount'
        /// </summary>
        [Fact]
        public void ReturnsCountTest()
        {
            // TODO unit test for the property 'ReturnsCount'
        }

        /// <summary>
        /// Test the property 'AdditionalFields'
        /// </summary>
        [Fact]
        public void AdditionalFieldsTest()
        {
            // TODO unit test for the property 'AdditionalFields'
        }

        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
    }
}
