/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseAnalyticsReportResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseAnalyticsReportResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseAnalyticsReportResult
        //private ResponseAnalyticsReportResult instance;

        public ResponseAnalyticsReportResultTests()
        {
            // TODO uncomment below to create an instance of ResponseAnalyticsReportResult
            //instance = new ResponseAnalyticsReportResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseAnalyticsReportResult
        /// </summary>
        [Fact]
        public void ResponseAnalyticsReportResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseAnalyticsReportResult
            //Assert.IsType<ResponseAnalyticsReportResult>(instance);
        }

        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }

        /// <summary>
        /// Test the property 'TotalMetrics'
        /// </summary>
        [Fact]
        public void TotalMetricsTest()
        {
            // TODO unit test for the property 'TotalMetrics'
        }

        /// <summary>
        /// Test the property 'Intervals'
        /// </summary>
        [Fact]
        public void IntervalsTest()
        {
            // TODO unit test for the property 'Intervals'
        }

        /// <summary>
        /// Test the property 'AdditionalFields'
        /// </summary>
        [Fact]
        public void AdditionalFieldsTest()
        {
            // TODO unit test for the property 'AdditionalFields'
        }

        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
    }
}
