/*
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TaxClassCountries
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaxClassCountriesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaxClassCountries
        //private TaxClassCountries instance;

        public TaxClassCountriesTests()
        {
            // TODO uncomment below to create an instance of TaxClassCountries
            //instance = new TaxClassCountries();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaxClassCountries
        /// </summary>
        [Fact]
        public void TaxClassCountriesInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaxClassCountries
            //Assert.IsType<TaxClassCountries>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Fact]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }

        /// <summary>
        /// Test the property 'TaxType'
        /// </summary>
        [Fact]
        public void TaxTypeTest()
        {
            // TODO unit test for the property 'TaxType'
        }

        /// <summary>
        /// Test the property 'States'
        /// </summary>
        [Fact]
        public void StatesTest()
        {
            // TODO unit test for the property 'States'
        }

        /// <summary>
        /// Test the property 'AdditionalFields'
        /// </summary>
        [Fact]
        public void AdditionalFieldsTest()
        {
            // TODO unit test for the property 'AdditionalFields'
        }

        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
    }
}
